config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :weather_grid

  get "/subscriptions/cancel_subscription" => "subscriptions#cancel_subscription"
  get "/subscriptions/update_card" => "subscriptions#update_card"
  post "/subscriptions/update_card_details" => "subscriptions#update_card_details"

  resources :subscriptions

  root to: 'home#index'

  mount StripeEvent::Engine, at: '/stripe-event' # provide a custom path

end

app/models/account.rb
class Account < ActiveRecord::Base
end

app/models/plan.rb
class Plan < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :async

  validate :email_is_unique, on: :create
  after_create :create_account

  private
    # Email should be unique in Account Model
    def email_is_unique
      # Do not validate email if errors are already present
      unless self.errors[:email].empty?
        return false
      end

      unless Account.find_by_email(email).nil?
        errors.add(:email, "is already being used")
      end
    end

    def create_account
      account = Account.new(:email => email)
      account.save!
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper ApplicationHelper
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @message = "Welcome user"
  end

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController

  before_action :authenticate_user!

  def new
    @plans = Plan.all
  end

  def edit
    @account  = Account.find(params[:id])
    @plans = Plan.all
  end

  def create
    ap "Inside create in subscription"
    ap params
    ap current_user

    # Get the credit card details submitted by the form
    token = params[:stripeToken]
    plan = params[:plan][:stripe_id]
    email = current_user.email
    current_account = Account.find_by_email(current_user.email)
    customer_id = current_account.customer_id
    current_plan = current_account.stripe_plan_id

    if customer_id.nil?
      # Create a Customer
      @customer = Stripe::Customer.create(
        :source => token,
        :plan => plan,
        :email => email
      )

      subcriptions = @customer.subscriptions
      @subscribed_plan = subcriptions.data.find { |o| o.plan.id == plan }

    else
      # Customer already exists
      @customer = Stripe::Customer.retrieve(customer_id)
      @subscribed_plan = create_or_update_subscription(@customer, current_plan, plan)

    end

    # get current period end - this is a unix timestamp
    current_period_end = @subscribed_plan.current_period_end
    active_until = Time.at(current_period_end)

    save_account_details(current_account, plan, @customer.id, active_until)

    redirect_to :root, :notice => "Succesfully subcribed to plan: #{Plan.find_by_stripe_id(plan).name}"

    rescue => e
      redirect_to :back, :flash => { :error => e.message }

  end

  def index
    @account = Account.find_by_email(current_user.email)
  end

  def cancel_subscription
    #Fetch customer from Stripe
    email = current_user.email
    current_account = Account.find_by_email(current_user.email)
    customer_id = current_account.customer_id
    current_plan = current_account.stripe_plan_id

    if current_plan.blank?
      raise "No plan found to unsubscribe from"
    end

    customer = Stripe::Customer.retrieve(customer_id)
    #Get customer subscriptions's
    subscriptions = customer.subscriptions
    #Find specific subscription
    current_subscribed_plan = subscriptions.data.find { |o| o.plan.id == current_plan}
    if current_subscribed_plan.blank?
      raise "Subscription not found!!!"
    end
    #Delete specific subscription
    current_subscribed_plan.delete
    #Update account model
    save_account_details(current_account, "", customer_id, Time.at(0).to_datetime)

    @message = "Subscription cancelled successfully"

    rescue => e
      redirect_to "/subscriptions", :flash => { :error => e.message }
  end

  def update_card

  end

  def update_card_details
    #Take the token given by stripe and set it on the customer object
    ap "KKKKKKKKKKKKKKKK"
    ap "params"
    ap params

    token = params[:stripeToken]
    current_account = Account.find_by_email(current_user.email)

    ap "BBBBBBBBBBBBBBB"
    ap "customer _ account"
    ap current_account

    ap "token"
    ap token

    customer_id = current_account.customer_id
    #Get customer from Stripe
    customer = Stripe::Customer.retrieve(customer_id)

    ap "BBBBBBBBBBBBBBB"
    ap "customer"
    ap customer

    #Set new card token
    customer.source = token
    customer.save

    redirect_to "/subscriptions", :notice => "Card updated succesfully"

    rescue => e
      redirect_to :action => "update_card", :flash => { :notice => e.message }

  end

  def save_account_details(account, plan, customer_id, active_until)
    # Customer created with a valid subcription
    # So, update Account model
    account.stripe_plan_id = plan
    account.customer_id = customer_id
    account.active_until = active_until
    account.save!
  end

  def create_or_update_subscription(customer, current_plan, new_plan)
    subscriptions = customer.subscriptions
    #Get current subscription
    current_subscription = subscriptions.data.find { |o| o.plan.id == current_plan }

    if current_subscription.blank?
      #No Current Subscription
      #Maybe subscription was cancelled or Credit Card was declined
      #So create new subscription for existing customer
      subscription = customer.subscriptions.create( {:plan => new_plan})
    else
      #Existing subscription found
      #So an upgrade or downgrade is occuring
      current_subscription.plan = new_plan
      subscription = current_subscription.save
    end

    return subscription
  end
end

app/controllers/weather_grid_controller.rb
class WeatherGridController < ApplicationController

  before_action :authenticate_user!

  def index
    #nothing yet
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    case flash_type
            when "success"
                "alert-success" #Green
            when "error"
                "alert-danger" #Red
            when "alert"
                "alert-warning" #Yellow
            when "notice"
                "alert-info" #Blue
            else
                flash_type.to_s
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/weather_grid_helper.rb
module WeatherGridHelper
end

app/views/home/index.html.erb
<%= link_to('Login', new_user_session_path) %>
<%= link_to('Logout', destroy_user_session_path, :method => :delete)%>
<%= link_to('Sign Up', new_user_registration_path) %>
<%= link_to('Manage Subscriptions', subscriptions_path) %>

<h1>
  <%= @message %>
</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SaasGuide</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |type, message| %>
    <div class="alert <%= bootstrap_class_for(type) %> alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= message.html_safe %>
    </div>
<% end %>

<%= yield %>

</body>
</html>

app/views/subscriptions/_creditcard.html.erb
<%= javascript_include_tag "https://js.stripe.com/v2/" %>

<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <%= form_tag "/subscriptions", id: "payment-form" do %>
      <span class="payment-errors text-danger"></span>

      <%= collection_select :plan, :stripe_id, @plans,
      :stripe_id, :name, {}, { class: "form-control" } %>

      <div class="form-group">
        <label for="number">Card</label>
          <input type="text" size="20" class="form-control" id="number" data-stripe="number">
      </div>

      <div class="form-group">
          <label for="cvc">CVC</label>
          <input type="text" size="4" class="form-control" id="cvc" data-stripe="cvc">
      </div>

      <label for="">Expiration (MM/YYYY)</label>
      <div class="form-group">
          <input type="text" size="2" class="form-control exp-field" id="exp" data-stripe="exp_month">
          <span> / </span>
          <input type="text" size="2" class="form-control exp-field" data-stripe="exp_year">
      </div>

      <input type="submit" class="btn btn-primary" value="Submit Payment">
    <% end %>
  </div>
</div>

<script type="text/javascript">
  Stripe.setPublishableKey('pk_test_z3yrL4LC2PGjjgjDRnfim1DK');
</script>

app/views/subscriptions/_plans.html.erb
<div class="row">
  <div class="col-sm-2 col-sm-offset-3">
<div class="plan_box">
  <h3>Plan Free</h3>
  <p>
    No Charge
    </br>
  </p>
</div>
  </div>
  <div class="col-sm-2">
<div class="plan_box">
  <h3>Plan Good</h3>
  <p>
    Good For Small Businesses
    </br>
  </p>
</div>
  </div>
  <div class="col-sm-2">
<div class="plan_box">
  <h3>Plan Awesome</h3>
  <p>
    Good For Enterprises
    </br>
  </p>
</div>
  </div>
</div>

app/views/subscriptions/cancel_subscription.html.erb
<h1>Cancel Subscription</h1>

<p>
  <%= @message %>
</p>

app/views/subscriptions/create.html.erb
<h1> Inside Create </h1>

app/views/subscriptions/edit.html.erb
Please choose your plan:
<%= render :partial => "plans" %>

<div class="row">
  <div class="col-sm-3 col-sm-offset-3">
    <%= form_tag "/subscriptions" do %>
          <span class="payment-errors text-danger"></span>

          <%= collection_select :plan, :stripe_id, @plans,
          :stripe_id, :name, {}, { class: "form-control" } %>

          </br>

          <input type="submit" class="btn btn-primary" value="Update Subscription">
    <% end %>
  </div>
</div>

app/views/subscriptions/index.html.erb
<% if @account.stripe_plan_id %>
  <% if @account.active_until > Time.now %>
    Your subscription is active until <%= @account.active_until %>
  <% else %>
    Your subscription is expired on <%= @account.active_until %>
  <% end %>

<% else %>
  No Subscriptions
<% end %>

</br>

<%= link_to  'Change Subscription', edit_subscription_path(@account.id),
  { class: "btn btn-primary"} %>

</br>
</br>

<%= link_to  'Cancel Subscription', subscriptions_cancel_subscription_path,
  { class: "btn btn-primary"} %>

</br>
</br>

<%= link_to  'Update Card', subscriptions_update_card_path,
  { class: "btn btn-primary"} %>

app/views/subscriptions/new.html.erb
<%= render :partial => "plans" %>

<%= render :partial => "creditcard" %>

app/views/subscriptions/update_card.html.erb
<%= javascript_include_tag "https://js.stripe.com/v2/" %>

<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <%= form_tag "/subscriptions/update_card_details", id: "payment-form" do %>
      <span class="payment-errors text-danger"></span>

      <div class="form-group">
        <label for="number">Card</label>
          <input type="text" size="20" class="form-control" id="number" data-stripe="number">
      </div>

      <div class="form-group">
          <label for="cvc">CVC</label>
          <input type="text" size="4" class="form-control" id="cvc" data-stripe="cvc">
      </div>

      <label for="">Expiration (MM/YYYY)</label>
      <div class="form-group">
          <input type="text" size="2" class="form-control exp-field" id="exp" data-stripe="exp_month">
          <span> / </span>
          <input type="text" size="2" class="form-control exp-field" data-stripe="exp_year">
      </div>

      <input type="submit" class="btn btn-primary" value="Submit Payment">
    <% end %>
  </div>
</div>

<script type="text/javascript">
  Stripe.setPublishableKey('pk_test_z3yrL4LC2PGjjgjDRnfim1DK');
</script>

app/views/weather_grid/index.html.erb
<h1>
Weather-Grid Index
</h1>